# sever port config
server:
  port: 8001

# oracle driver config
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@oracle.team-greedy.com:1521:xe
    username: C##ROTUTEE
    password: ROTUTEE
    hikari:
      auto-commit: false

    servlet:
      multipart:
        max-file-size: 50MB
        max-request-size: 500MB
# jpa config
  jpa:
    generate-ddl: false
    show-sql: true
    database: oracle
    properties:
      hibernate:
        '[format_sql]': true
        ddl-auto: validate